Milestone 2
KerronKing/react-redux-bookstore pull request #2
Opened 2020-02-20 16:27 UTC by KerronKing

In this milestone, we:
- Prepared the directory structure.
- Created a components directory in the src folder for all the presentational components.
- Created a containers directory in the src folder for all the container components.
- Created a actions directory with the index.js file where you’ll define all the Redux actions.
- Created a reducers directory with two files: books.js and index.js.
- Implement the App, Booklist, Bookform and Book components.
- Defined a constant with a collection containing the book categories: ["Action", "Biography", "History", "Horror", "Kids", "Learning", "Sci-Fi"].
- Defined the Redux actions and reducers
- Implemented the books.js reducer.
- Initialized the Redux store.

2020-02-20 19:15 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this milestone :+1: just a few things left to work on............ :slightly_smiling_face: 
 
**Kindly checkout my comments below;**

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-02-20 19:15 UTC, bellom commented on .eslintrc.json
> +      "react/forbid-prop-types": 0
You made just one changes in this file 😄, check out the [microverse-linter-config](https://github.com/microverseinc/linters-config/tree/master/javascript)
![image](https://user-images.githubusercontent.com/31897434/73417568-ca44bd00-4318-11ea-8a5e-fedabd629b8c.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

2020-02-20 19:15 UTC, bellom commented on src/components/bookslist.js
> +import React from 'react';
`booklist` should be inside the `container` folder because you're connecting to the redux store, it is not one of the presentional components right?
![image](https://user-images.githubusercontent.com/31897434/74967936-3dbe8380-541a-11ea-9a0a-a441a84efc59.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-02-20 19:15 UTC, bellom commented on src/reducers/bookReducer.js
> +const initialState = {
let use `combineReducers` to combine our `bookReducer.js`, for now, our combineReducer will only take in just the  `bookReducer.js`
![image](https://user-images.githubusercontent.com/31897434/74969031-2b454980-541c-11ea-8818-b3ed6c60fc12.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-02-21 10:30 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good job implementing the suggested changes from @bellom.

Check out the optional comment before merging. :relaxed: 

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-02-21 10:30 UTC, bolah2009 commented on src/components/booksform.js
> +          />
[Optional]

Let's add the `required` attribute to help with validation

2020-02-21 17:55 UTC, merged